
version: '3.8'

services:
  spark-connect:
    image: apache/spark:3.5.1
    container_name: spark-connect-server
    user: root  # <-- Garante permissão para o download do pacote Connect
    ports:
      - "15002:15002"
      - "4040:4040"
    # Roda o servidor diretamente em primeiro plano
    command: >
      /opt/spark/bin/spark-submit 
      --class org.apache.spark.sql.connect.service.SparkConnectServer 
      --packages org.apache.spark:spark-connect_2.12:3.5.1